[tool.black]
line-length = 120

[project]
name = "aero"
version = "0.0.0"
dependencies = [
    "requests>=2.25.1",
    "rasterio>=1.2.10",
    "click>=8.1.8",
    "pyright>=1.1.403",   
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["src"]

[tool.pyright]
typeCheckingMode = "basic"
stubPath = "typings"
typeshedPaths = ["typings"]
reportMissingModuleSource = false

executionEnvironments = [
  { root = "devtools", pythonVersion = "3.12" },
  { root = "src", pythonVersion = "3.10" },
]

ignore = ["typings"]
